project:
  type: website

website:
  title: "Ena Zou"
  favicon: favicon_white.jpg
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Experiences.qmd
        text: Experiences
      - href: Projects.qmd
        text: Projects
  page-footer:
      right: "&copy; 2024 Ena Zou"
      border: false
format:
  html: 
    theme: cosmo
    css: 
      - main.css
    toc: true

execute:
  freeze: auto
